# Permalinks
#
permalink: /:categories/:year/:month/:day/:title
# permalink: "/:title"

highlighter: rouge # pygments was old highlighter

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true


# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Facebook settings
fb_admins:
avatar:
locale:

# Image settings
image_base:          /images/

# Do not copy these file to the output directory
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

#fb_appid:           337414769782635

# Setup
title : Stefan Avey
tagline: blog
author :
  name : Stefan Avey
  email :
  twitter :
  feedburner :
production_url : http://stefanavey.github.io
paginate: 3
# baseurl:             "/sa"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: compressed

# About/contact
author:
  name:              Stefan Avey
  url:               https://stefanavey.me
  # email:             blah@gmail.com

# Custom vars
version:             1.0.0
github:
  username: stefanavey
  repository: stefanavey.github.io

# Google sitemap generation
gems:
  - jekyll-sitemap

# Conversion
markdown:    kramdown
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes"]

kramdown:
  auto_ids: true

pages_list:
  About: '/about/'
  # Hobby projects: '/hobbies/'
  Tags: '/tags/'
  RSS Feed: '/rss.xml'
  Blog Roll: '/blogroll/'

picture:
  source: "assets/imgs/_fullsize"
  output: "generated"
  markup: "picture"

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  JB:
  comments :
    provider : disqus
    disqus :
      short_name : stefantastic
  #   livefyre :
  #     site_id : 123
  #   intensedebate :
  #     account : 123abc
  #   facebook :
  #     appid : 123
  #     num_posts: 5
  #     width: 580
  #     colorscheme: light
